Repository COMP4350TheHouse/Casino, pull requests merged in 2025-02, with the labels that each got.

#48 Mysql setup
  .dockerignore
  .gitignore
  Dockerfile
  Gemfile
  Gemfile.lock
  GetStarted.md
  config/database.yml
  db/schema.rb
  docker-compose.yml
  init.sql
  log/development.log
  storage/.keep
  storage/development.sqlite3
Labels: code spike, dev task

#52 Add user accounts, authentication, and wallet balance [#31, etc.]
  Gemfile
  Gemfile.lock
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/authentication.rb
  app/controllers/passwords_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/mailers/passwords_mailer.rb
  app/models/current.rb
  app/models/session.rb
  app/models/user.rb
  app/views/passwords/edit.html.erb
  app/views/passwords/new.html.erb
  app/views/passwords_mailer/reset.html.erb
  app/views/passwords_mailer/reset.text.erb
  app/views/sessions/new.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20250212035032_create_users.rb
  db/migrate/20250212035033_create_sessions.rb
  db/migrate/20250212055117_add_balance_to_users.rb
  db/migrate/20250212055215_add_username_to_users.rb
  db/schema.rb
  log/development.log
  log/test.log
  test/controllers/users_controller_test.rb
  test/fixtures/users.yml
  test/mailers/previews/passwords_mailer_preview.rb
  test/models/user_test.rb
Labels: dev task

#55 Change local and testing versions of MySQL to the LTS version
  .github/workflows/rubyonrails.yml
  docker-compose.yml
  log/development.log
Labels: bug

#56 Adjust GetStarted.md to fix clarity/mistakes
  GetStarted.md
Labels: documentation

#68 Remove development.log and other log files from the GitHub repo
  .gitignore
  log/.keep
  log/development.log
  log/test.log
Labels: bug, code spike

#73 Add tests for horse racing issue
  app/controllers/horse_race_controller.rb
  app/models/horse.rb
  test/controllers/horse_races_controller_test.rb
  test/controllers/lobby_controller_test.rb
  test/fixtures/horses.yml
Labels: dev task
