Repository COMP4350TheHouse/Casino, pull requests merged in 2025-03, with the labels that each got.

#102 Add CD pipeline for building and pushing docker images
  .github/workflows/rubyonrails_cd.yml
  Dockerfile
Labels: code spike, dev task

#104 Update gems 2025-03-08
  Gemfile.lock
Labels: Maintenance

#107 Add Casino Header [#96]
  Gemfile
  Gemfile.lock
  app/assets/images/account-icon.svg
  app/assets/images/chat-icon.svg
  app/assets/stylesheets/application.css
  app/assets/stylesheets/lobby.css
  app/assets/stylesheets/partials/account_menu.css
  app/assets/stylesheets/partials/header.css
  app/controllers/application_controller.rb
  app/views/layouts/application.html.erb
  app/views/lobby/index.html.erb
  app/views/shared/_account_menu.html.erb
  app/views/shared/_header.html.erb
Labels: dev task

#112 [#111] Change stylesheet include in application.html.erb
  Gemfile.lock
  app/views/layouts/application.html.erb
  app/views/lobby/index.html.erb
  app/views/passwords/edit.html.erb
  app/views/passwords/new.html.erb
  app/views/sessions/new.html.erb
  app/views/shared/_account_menu.html.erb
  app/views/shared/_header.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
Labels: bug

#113 [#106] Remodel lobby
  app/assets/stylesheets/lobby.css
  app/assets/stylesheets/partials/lobby_roulette_wheel.css
  app/views/lobby/index.html.erb
  app/views/shared/_lobby_roulette_wheel.html.erb
  test/controllers/lobby_controller_test.rb
Labels: dev task

#118 116 Update horse racing styling
  Gemfile.lock
  GetStarted.md
  README.md
  app/assets/fonts/Caveat-VariableFont_wght.ttf
  app/assets/images/betting_closed.png
  app/assets/images/black_casino_chip.png
  app/assets/images/blue_casino_chip.png
  app/assets/images/green_casino_chip.png
  app/assets/images/green_casino_felt.jpg
  app/assets/images/paper.png
  app/assets/images/pin.png
  app/assets/images/pink_casino_chip.png
  app/assets/images/purple_casino_chip.png
  app/assets/images/red_casino_chip.png
  app/assets/images/white_casino_chip.png
  app/assets/images/yellow_casino_chip.png
  app/assets/stylesheets/chip_selection.css
  app/assets/stylesheets/horse_betting.css
  app/assets/stylesheets/lobby.css
  app/assets/stylesheets/partials/lobby_roulette_wheel.css
  app/assets/stylesheets/roulette_assets.css
  app/assets/stylesheets/roulette_board.css
  app/assets/stylesheets/roulette_wheel.css
  app/controllers/application_controller.rb
  app/controllers/lobby_controller.rb
  app/controllers/roulette_controller.rb
  app/javascript/roulette_logic.js
  app/models/bet.rb
  app/models/horse.rb
  app/models/payout_calculator.rb
  app/views/horse_race/index.html.erb
  app/views/layouts/application.html.erb
  app/views/lobby/index.html.erb
  app/views/passwords/edit.html.erb
  app/views/passwords/new.html.erb
  app/views/roulette/roulette_board.html.erb
  app/views/sessions/new.html.erb
  app/views/shared/_account_menu.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_lobby_roulette_wheel.html.erb
  app/views/shared/horse_race/bet/_form.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20250305225723_create_bets.rb
  db/schema.rb
  test/controllers/horse_races_controller_test.rb
  test/controllers/lobby_controller_test.rb
  test/controllers/roulette_controller_test.rb
  test/fixtures/users.yml
Labels: dev task

#105 83 user chat
  app/assets/stylesheets/application.css
  app/assets/stylesheets/chat.css
  app/channels/application_cable/channel.rb
  app/channels/global_channel.rb
  app/channels/horse_race_channel.rb
  app/channels/roulette_channel.rb
  app/controllers/chat_controller.rb
  app/controllers/horse_race_controller.rb
  app/helpers/chat_helper.rb
  app/javascript/application.js
  app/javascript/channels/consumer.js
  app/javascript/channels/global_channel.js
  app/javascript/channels/horse_race_channel.js
  app/javascript/channels/horse_wager_channel.js
  app/javascript/channels/index.js
  app/javascript/channels/roulette_channel.js
  app/javascript/roulette_logic.js
  app/views/chat/send.html.erb
  app/views/horse_race/betting.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_chat.html.erb
  config/importmap.rb
  config/routes.rb
  db/schema.rb
  test/channels/global_channel_test.rb
  test/channels/horse_race_channel_test.rb
  test/channels/roulette_channel_test.rb
  test/controllers/chat_controller_test.rb
Labels: enhancement

#126 [#119] Add daily allowance code
  app/controllers/application_controller.rb
  app/jobs/reset_allowances_job.rb
  app/models/user.rb
  config/initializers/scheduler.rb
  db/migrate/20250317142055_add_allowance_paid_to_users.rb
  db/schema.rb
  test/controllers/horse_races_controller_test.rb
  test/controllers/lobby_controller_test.rb
  test/fixtures/users.yml
  test/jobs/reset_allowances_job_test.rb
Labels: dev task

#124 [#123] Use the actual image name in docker-compose
  docker-compose.yml
Labels: bug

#128 [#119] Add tests for reset allowance job and pay allowance
  test/fixtures/users.yml
  test/jobs/reset_allowances_job_test.rb
  test/models/user_test.rb
Labels: dev task

#131 [#130] Make user chat available on all pages
  app/views/layouts/application.html.erb
Labels: bug

#137 136 use latest tag
  .github/workflows/rubyonrails_cd.yml
  docker-compose.yml
Labels: dev task

#143 [#103] Update gems
  Gemfile.lock
  db/schema.rb
Labels: Maintenance

#144 140 enhance user chat
  app/assets/images/send.svg
  app/assets/stylesheets/application.css
  app/assets/stylesheets/chat.css
  app/views/shared/_chat.html.erb
Labels: dev task

#145 [#138] Move security scan to it's own job
  .github/workflows/rubyonrails.yml
  config/brakeman.yml
Labels: dev task

#154 [#148] Remove password reset link on sign in page
  app/controllers/passwords_controller.rb
  app/mailers/passwords_mailer.rb
  app/views/passwords/edit.html.erb
  app/views/passwords/new.html.erb
  app/views/passwords_mailer/reset.html.erb
  app/views/passwords_mailer/reset.text.erb
  app/views/sessions/new.html.erb
  config/routes.rb
  test/mailers/previews/passwords_mailer_preview.rb
Labels: dev task

#160 Fix typo in image name
  .github/workflows/rubyonrails_cd.yml
Labels: bug
